/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArtRouteImport } from './routes/art'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresSlugRouteImport } from './routes/stores.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresRoute,
} as any)
const StoresSlugRoute = StoresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/art': typeof ArtRoute
  '/brand': typeof BrandRoute
  '/careers': typeof CareersRoute
  '/franchise': typeof FranchiseRoute
  '/menu': typeof MenuRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/stores': typeof StoresRouteWithChildren
  '/terms': typeof TermsRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/art': typeof ArtRoute
  '/brand': typeof BrandRoute
  '/careers': typeof CareersRoute
  '/franchise': typeof FranchiseRoute
  '/menu': typeof MenuRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/art': typeof ArtRoute
  '/brand': typeof BrandRoute
  '/careers': typeof CareersRoute
  '/franchise': typeof FranchiseRoute
  '/menu': typeof MenuRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/stores': typeof StoresRouteWithChildren
  '/terms': typeof TermsRoute
  '/stores/$slug': typeof StoresSlugRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/art'
    | '/brand'
    | '/careers'
    | '/franchise'
    | '/menu'
    | '/news'
    | '/privacy'
    | '/stores'
    | '/terms'
    | '/stores/$slug'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/art'
    | '/brand'
    | '/careers'
    | '/franchise'
    | '/menu'
    | '/news'
    | '/privacy'
    | '/terms'
    | '/stores/$slug'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/art'
    | '/brand'
    | '/careers'
    | '/franchise'
    | '/menu'
    | '/news'
    | '/privacy'
    | '/stores'
    | '/terms'
    | '/stores/$slug'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtRoute: typeof ArtRoute
  BrandRoute: typeof BrandRoute
  CareersRoute: typeof CareersRoute
  FranchiseRoute: typeof FranchiseRoute
  MenuRoute: typeof MenuRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  StoresRoute: typeof StoresRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof StoresRoute
    }
    '/stores/$slug': {
      id: '/stores/$slug'
      path: '/$slug'
      fullPath: '/stores/$slug'
      preLoaderRoute: typeof StoresSlugRouteImport
      parentRoute: typeof StoresRoute
    }
  }
}

interface StoresRouteChildren {
  StoresSlugRoute: typeof StoresSlugRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresSlugRoute: StoresSlugRoute,
  StoresIndexRoute: StoresIndexRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtRoute: ArtRoute,
  BrandRoute: BrandRoute,
  CareersRoute: CareersRoute,
  FranchiseRoute: FranchiseRoute,
  MenuRoute: MenuRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  StoresRoute: StoresRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
